### ISSUE TITLE
is this open to maintenance?

### ISSUE THREAD

**Issue by strideynet** [adin234/materialize-datatables#1]
Might fork this as it's just what I needed!

**Comment by adin234** [comment]
ofcourse. do as you wish :)

**Comment by NathanUrwin** [comment]
@strideynet Did you ever come up with anything?

**Comment by strideynet** [comment]
@tuxredux Nope. I ended up using a different CSS framework.

**Comment by NathanUrwin** [comment]
@strideynet Which framework if you don't mind me asking?

**EDIT:** I'm actually going to use [MDL](https://github.com/google/material-design-lite) and [MDC-Web](https://github.com/material-components/material-components-web) by Google, but I'm still interested in what you went with!

The real reason for my edit though is I found a working implementation of Materialize and DataTables [in this project](https://github.com/viewflow/django-material) if anyone is interested.
